#### Name: Rathod Nikhil 
#### Enrollment No : 24030501039
#### Roll No : 135
#### Subject : IAT

## Step 1.import the Numpy library

In [2]:
import numpy as np

## Step 2. cretae a 1D array of numbers

In [60]:
a=np.arange(11)
print(a)
print(type(a))

[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [5]:
a=np.arange(2,9)
a


array([2, 3, 4, 5, 6, 7, 8])

## step 3. Reshape 1D to 2D Array

In [7]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## step 4. cretae a Linespace array

In [8]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## step 5. Create a randome Numberd Array

In [9]:
np.random.rand(2)

array([0.71689405, 0.35419928])

In [10]:
np.random.rand(2,4)

array([[0.53439756, 0.59770491, 0.21728327, 0.62350806],
       [0.79196683, 0.7849771 , 0.07019256, 0.7205068 ]])

## step 6. Create a Randome Integer Array

In [12]:
np.random.randint(1,100,size=10)

array([38, 65, 56,  3, 12, 36, 42,  2, 93, 16], dtype=int32)

In [13]:
np.random.randint(1,100,size=(2,4))

array([[94, 28, 36, 38],
       [ 3, 50, 90, 83]], dtype=int32)

## step 7. cretae a 1D Array and get Max,Min,ArgMax,ArMIn

In [14]:
arr=np.random.randint(1,100,size=(10))
arr

array([82, 89, 29, 22, 62, 30,  3,  9, 34, 70], dtype=int32)

In [15]:
arr.max()

np.int32(89)

In [16]:
arr.min()

np.int32(3)

In [17]:
arr.argmax()

np.int64(1)

In [18]:
arr.argmin()

np.int64(6)

## step 8. Indexing in 1D Array

In [19]:
arr[8]

np.int32(34)

In [20]:
arr[1:5]

array([89, 29, 22, 62], dtype=int32)

## step 9. Indexing in 2D Array

In [22]:
arr2d=arr.reshape(2,5)
arr2d

array([[82, 89, 29, 22, 62],
       [30,  3,  9, 34, 70]], dtype=int32)

In [23]:
arr2d[0]

array([82, 89, 29, 22, 62], dtype=int32)

In [24]:
arr2d[0][1]
arr2d[0,1]

np.int32(89)

In [25]:
arr2d[:1,2:]

array([[29, 22, 62]], dtype=int32)

## Step 10. Conditional Selection

In [28]:
arr[arr>4]

array([82, 89, 29, 22, 62, 30,  9, 34, 70], dtype=int32)

In [29]:
arr2d[arr2d>2]

array([82, 89, 29, 22, 62, 30,  3,  9, 34, 70], dtype=int32)

## Step 1. Import the necessary libraries

In [31]:
import pandas as pd

## STep 3. Assign it to a variable called users and use the 'user_is' as index

In [2]:
import pandas as pd

users = pd.read_csv(
    "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",
    sep="|",
    header=None,
    names=["user_id", "age", "gender", "occupation", "zip_code"],
    index_col="user_id"  
)

print(users.head(25))


         age  gender     occupation  zip_code
user_id                                      
user_id  age  gender     occupation  zip_code
1         24       M     technician     85711
2         53       F          other     94043
3         23       M         writer     32067
4         24       M     technician     43537
5         33       F          other     15213
6         42       M      executive     98101
7         57       M  administrator     91344
8         36       M  administrator     05201
9         29       M        student     01002
10        53       M         lawyer     90703
11        39       F          other     30329
12        28       F          other     06405
13        47       M       educator     29206
14        45       M      scientist     55106
15        49       F       educator     97301
16        21       M  entertainment     10309
17        30       M     programmer     06355
18        35       F          other     37212
19        40       M      libraria

## step 4. See the first 25 entries

In [36]:
users.head(25)

age  gender     occupation  zip_code
user_id                                      
user_id  age  gender     occupation  zip_code
1         24       M     technician     85711
2         53       F          other     94043
3         23       M         writer     32067
4         24       M     technician     43537
5         33       F          other     15213
6         42       M      executive     98101
7         57       M  administrator     91344
8         36       M  administrator     05201
9         29       M        student     01002
10        53       M         lawyer     90703
11        39       F          other     30329
12        28       F          other     06405
13        47       M       educator     29206
14        45       M      scientist     55106
15        49       F       educator     97301
16        21       M  entertainment     10309
17        30       M     programmer     06355
18        35       F          other     37212
19        40       M      librarian     02138
20        42       F      homemaker     95660
21        26       M         writer     30068
22        25       M         writer     40206
23        30       F         artist     48197
24        21       F         artist     94533

## step 5. See the last 10 entries

In [37]:
users.tail(10)

age gender     occupation zip_code
user_id                                   
934      61      M       engineer    22902
935      42      M         doctor    66221
936      24      M          other    32789
937      48      M       educator    98072
938      38      F     technician    55038
939      26      F        student    33319
940      32      M  administrator    02215
941      20      M        student    97229
942      48      F      librarian    78209
943      22      M        student    77841

## Step 6. What is the number of observation is the dataset?

In [38]:
users.shape[0]

944

## Step 7. What is the number of columns in the dataset?

In [39]:
users.shape[1]

4

## Step 8. Print the name of all the columns.

In [41]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

## Step 9. How is the dataset indexed?

In [42]:
users.index

Index(['user_id', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '934', '935', '936', '937', '938', '939', '940', '941', '942', '943'],
      dtype='object', name='user_id', length=944)

## Step 10. What is the data type of each column?

In [43]:
users.dtypes

age           object
gender        object
occupation    object
zip_code      object
dtype: object

## Step 11. Print only the occupation column

In [44]:
users['occupation']

user_id
user_id       occupation
1             technician
2                  other
3                 writer
4             technician
               ...      
939              student
940        administrator
941              student
942            librarian
943              student
Name: occupation, Length: 944, dtype: object

## Step 12. How many different occupations are in this dataset?

In [46]:
users.occupation.nunique()

22

## Step 13. What is the most frequent occupation?

In [47]:
users.occupation.value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

## Step 14. Summarize the DataFrame.

In [48]:
users.describe()

age gender occupation zip_code
count   944    944        944      944
unique   62      3         22      796
top      30      M    student    55414
freq     39    670        196        9

## Step 15. Summarize all the columns

In [49]:
users.describe(include='all')

age gender occupation zip_code
count   944    944        944      944
unique   62      3         22      796
top      30      M    student    55414
freq     39    670        196        9

## Step 16. Summarize only the occupation column

In [4]:
users['occupation'].describe()

count         944
unique         22
top       student
freq          196
Name: occupation, dtype: object

## Step 17. What is the mean age of users?

In [30]:
users['age'] = pd.to_numeric(users['age'],errors='coerce')
age = users['age'].mean()
age

34.05196182396607

## Step 18. Wgat is the age with least occurrence?

In [59]:
users.age.value_counts().tail()

age
age    1
11     1
66     1
10     1
73     1
Name: count, dtype: int64