<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="150" height="200"/></a>
<pre>
<center><b><h2> Python for Data Science - 2305CS303 </b></center>
<center><b><h2>Lab - 8</b></center>    
<left><b><h3>Roll No. : 135</b></left>  
<left><b><h3>Name : Nikhil Rathod</b></left>   
<pre>    

### 1. import numpy library.

In [1]:
import numpy as np

### 2.Create an array of 10 zeros

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3. Create an array of 10 ones.


In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 4. Create an array of 10 fives

In [28]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

### 5. Create an array of integers from 10 to 50.

In [10]:
np.arange(1,51,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 6. Create an array of all the even integers from 10 to 50.

In [15]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### 7. Create a 3x3 matrix with values ranging from 0 to 8.

In [24]:
a1 = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
a1

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

### 8. Create a 3x3 identity matrix.

In [31]:
a2 = np.eye(3)
print(a2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 9. Use Numpy to generate a random number between 0 and 1


In [34]:
a3 = np.random.randint(0,1,2)
print(a3)

[0 0]


### 10. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution.

In [37]:
rand_no = np.random.randn(25)
print(rand_no)

[-0.6664252  -1.32417056  0.45843106 -2.6578759  -0.4525991   2.28058298
  1.79945796  1.21785238 -0.09991865 -0.32802129 -0.28432504  0.77023519
  0.69401549 -1.10606506 -0.20739018 -0.35200384  0.83649324  0.16638486
  0.96126215  0.79823611 -0.44698955  1.29377777  0.87299239  0.98673143
  1.30201239]


### 11. Create linspace array

In [39]:
np.linspace(0,10,12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

### 12. Create an array of 20 linearly spaced points between 0 and 1. 

In [41]:
a5 = np.linspace(0,1,20)
a5

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### 13. Create Random Integer Array

In [45]:
arr = np.random.randint(0,100, size = 10)
arr

array([97, 12, 86, 35, 36, 54, 66, 63, 17, 79])

### 14. Create Random Integer Array and Reshape that Array

In [54]:
a = np.random.randint(0,100,12).reshape(3,4)
a

array([[39, 80, 57, 97],
       [16, 19, 87, 57],
       [70,  2, 85, 14]])